### ISSUE TITLE
upload files to static link

### ISSUE THREAD

**Issue by congaterori** [MVKozlov/GMGoogleDrive#14]
upload files to static link?
i need to upload the files in pc1 and download the files in pc2 but pc2 doesn't know the link
so can you make a static link? to upload files and download files

**Comment by MVKozlov** [comment]
Sorry, can't check it now.

You may try to use `Get-GDriveItemProperty -Property webViewLink, webContentLink` to get this link

**Comment by MVKozlov** [comment]
If this is not what you want and you know how to do this, please link to the doc, I'm try implement this in the module
