### ISSUE TITLE
How to import this module?

### ISSUE THREAD

**Issue by shinayser** [MVKozlov/GMGoogleDrive#15]
Sorry for the stupid question, I just started learning powershell right now.

I've read the README file but haven't found how to import it into my scripts.
How can I do that?

**Comment by MVKozlov** [comment]
as any other module :)

in commandline/script
`Import-Module GMGoogleDrive`
in script only
`#Requires -Module GMGoogleDrive`

**Comment by shinayser** [comment]
Amazing!! Thanks for the answer!

May I ask how you made for it to be available like this? 
I mean, just publishing it to GitHub makes it available globaly like that?

**Comment by MVKozlov** [comment]
No
Seems you install it from [PowershellGallery ](https://www.powershellgallery.com/packages/GMGoogleDrive) :)

And publishing a module makes it available for global installation through the `PowerShellGet` and `PackageManagement` modules installed with PSv5.1.
