### ISSUE TITLE
(1.0.4.2) Endless PUT do-loop in Set-GDriveItemContent for files > 4MB

### ISSUE THREAD

**Issue by DeeTigIT** [MVKozlov/GMGoogleDrive#16]
Uploading a file pf3910287872.tmp with 5144978 bytes results in an endless loop.
Inspecting the code of I see 2 times: $UploadedSize = ([long]$matches[2]) + 1
**Could it be that $matches is missing in the code?**

VERBOSE: URI: https://www.googleapis.com/drive/v3/files/
VERBOSE: URI: https://www.googleapis.com/drive/v3/files/?supportsAllDrives=true&pageSize=100&q=name
VERBOSE: URI: https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=r
VERBOSE: Metadata upload, resumable, 5144978 bytes, application/octet-stream
VERBOSE: Performing the operation "Uploading file named 'pf3910287872.tmp' from [d:\Temp\pf39102878
VERBOSE: POST https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=r
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8
VERBOSE: ResumeID: ADPycdsBKYRQlfKVLLT2N-eS-Oe-Gpka8--qkjaPZgRpJm2Q-au7T6hHj2mssnH2X4KpPrxADwypmxbC
VERBOSE: Received Range:
VERBOSE: Performing the operation "Uploading file named 'pf3910287872.tmp' from [d:\Temp\pf39102878
VERBOSE: Multiple requests upload
VERBOSE: Content-Length: 4194304, Content-Range bytes 0-4194303/5144978, readed: 4194304
VERBOSE: PUT https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=re
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8
VERBOSE: Received Range: bytes=0-4194303
VERBOSE: Stream Position: 4194304, UploadedSize:4194304
VERBOSE: Content-Length: 950674, Content-Range bytes 4194304-5144977/5144978, readed: 950674
VERBOSE: PUT https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=re
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8
VERBOSE: Received Range: bytes=0-4194303
VERBOSE: Stream Position: 5144978, UploadedSize:4194304
VERBOSE: Fast Forward to:4194304
VERBOSE: Content-Length: 950674, Content-Range bytes 4194304-5144977/5144978, readed: 950674
VERBOSE: PUT https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=re
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8
VERBOSE: Received Range: bytes=0-4194303
VERBOSE: Stream Position: 5144978, UploadedSize:4194304
VERBOSE: Fast Forward to:4194304
VERBOSE: Content-Length: 950674, Content-Range bytes 4194304-5144977/5144978, readed: 950674
VERBOSE: PUT https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=re
VERBOSE: received 0-byte response of content type text/plain; charset=utf-8
VERBOSE: Received Range: bytes=0-4194303
VERBOSE: Stream Position: 5144978, UploadedSize:4194304
VERBOSE: Fast Forward to:4194304
VERBOSE: Content-Length: 950674, Content-Range bytes 4194304-5144977/5144978, readed: 950674
VERBOSE: PUT https://www.googleapis.com/upload/drive/v3/files/?supportsAllDrives=true&uploadType=re
etc. etc

**Comment by MVKozlov** [comment]
You did not write under which version of PS you run this command.

Seems it's something of PSv7 and it have some breaking changes with `Invoke-WebRequest` cmdlet

I have a bunch of errors with it and I try to fix it soon

**Comment by DeeTigIT** [comment]
Indeed, I did some testing with PS7 with Set-GDriveItemContent 
In my test, unfortunately, some trial PS7 adaptations where still present. Excuses for that.
Using the pure 1.0.4.2 version of this function there is no looping. 
Perhaps this issue should therefore be renamed.

My trials in the zip (code tagged with # PS7):

[PS7 trials Set-GDriveItemContent.zip](https://github.com/MVKozlov/GMGoogleDrive/files/10077299/PS7.trials.Set-GDriveItemContent.zip)

Note: I'm not an experienced developer (yet).

**Comment by MVKozlov** [comment]
Thanks, I'll see it tomorrow. I already prepare some fix and your. trials just in place. 

I have not yet used my module with version 7 and was surprised to find 8 month old bug reports about it on reddit and not here. with links to module repository :)

**Comment by MVKozlov** [comment]
@DeeTigIT, please test latest commit

**Comment by DeeTigIT** [comment]
Hello Max,

I did some file uploading testing using the latest git repository GMGoogleDrive: 
Using the following file sizes:
LT 4194304 bytes (1 times a PUT)
EQ 4194304 bytes (1 times a PUT)
GT 4194304 bytes (n times a PUT, n >= 2)

Both with PSVersion: 5.1.19041.1682 and PSVersion: 7.3.0

After uploading files to Google Drive:
- download the files 
- compare byte-by-byte to the original files

My conclusions:
- setting file content with Set-GDriveItemContent works as aspected
- no endless looping 

**Thanks!**

**Comment by MVKozlov** [comment]
closed in v1.1.00
