### ISSUE TITLE
Question about oauth sign in allowing

### ISSUE THREAD

**Issue by zniezelski** [MVKozlov/GMGoogleDrive#2]
Hello,

Thanks for the script. 

I'm trying to create a script that would be configured as a daily windows scheduled task to check some dates of backup files that get uploaded to Google Drive.

I put together a script using the readme and it prompts to sign in to google and asks to allow the user to "view and manage the files in your google drive".

Could someone help me automate this part?

Thanks,

Zach

**Comment by MVKozlov** [comment]
Seems you use some manual steps in your code.
To automate such task you need

Manually:
1. get client id and client secret
2. get refresh token
3. save it securely

By Script:
1. get refresh code, client id and client secret from secure storage
2. use it to get access code
3. use this access code

**Comment by MVKozlov** [comment]
my script looks like this
``` powershell
# [...]
$Credentials = Get-ProtectedCredentials # your access to secure storage

try {
    Write-Host "Getting Access token"
    $Token = Get-GDriveAccessToken -ClientID $Credentials.ClientID -ClientSecret $Credentials.ClientSecret -RefreshToken $Credentials.RefreshToken
    $Token | Add-Member -MemberType NoteProperty -Name expires -Value ([DateTime]::Now.AddSeconds($Token.expires_in))
    Write-Host "Token expires at $($Token.expires)"
}
catch {
    Write-Warning "Error getting Access token $_"
    Get-GDriveError $_
}
if ($Token) {
    $Summary = Get-GDriveSummary -AccessToken $Token.access_token -ErrorAction Stop
    # [...]
}
```

**Comment by zniezelski** [comment]
Thanks for the help!

I'm trying to run your script and i'm getting hung up on Get-ProtectedCredentials not being available. Is there an additional module I need to load for that?

Thanks,

Zach

**Comment by MVKozlov** [comment]
I't's my own implementation of protected storage
Can't paste it here, it strictly tied to my environment and have no time to clear it for free distribution, but for simplicity and for TEST ONLY! you can just
``` powershell
[PSCustomObject]@{
  ClientID = 'yourclientid'
  ClientSecret = 'yourclientsecret'
 RefreshToken = 'yourRefreshtoken'
} | ConvertTo-Json | Set-Content somefile
```
and use it as
``` powershell
function Get-ProtectedCredentials {
  Get-Content 'somefile' | ConvertFrom-Json
}
```
if you add `ConvertXXX-SecureString` before `Set-Content` and after `Get-Content` you can add some security layer

**Comment by MVKozlov** [comment]
these function can help you
``` powershell
function Protect-String {
<#
	.SYNOPSIS
		Convert String to textual form of SecureString
	.PARAMETER String
		String to convert
	.OUTPUTS
		String
#>
param(
	[Parameter(Mandatory=$true, ValueFromPipeline=$true)]
	[string]$String
)
PROCESS {
	$String | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString
}
}

function Unprotect-String {
<#
	.SYNOPSIS
		Convert SecureString to plain string
	.PARAMETER String
		String to convert
	.PARAMETER SecureString
		SecureString to convert
	.OUTPUTS
		String
#>
[CmdletBinding(DefaultParameterSetName='s')]
param(
	[Parameter(Mandatory=$true, ValueFromPipeline=$true, Position=0, ParameterSetName='s')]
	[string]$String,
	[Parameter(Mandatory=$true, ValueFromPipeline=$true, Position=0, ParameterSetName='ss')]
	[SecureString]$SecureString
)
PROCESS {
	if ($String) {
		$SecureString = $String | ConvertTo-SecureString
	}
	if ($SecureString) {
		(New-Object System.Net.NetworkCredential '', ($SecureString)).Password
	}
}
}
```
Usage:
``` powershell
# save credentials to file (manually)
$YourCredentialObject | ConvertTo-Json | Protect-String | Set-Content file
#
# use saved credentials: in scheduled script
$decodedstring = Get-Content file | Unprotect-String
# and then 
$Credential = ConvertFrom-JSon $decodedstring
```
The credentials must be saved on the same computer and by the same user, where and by whom they will be used

**Comment by zniezelski** [comment]
MVKozlov,

Thanks a lot!!! That all worked for me!

Zach
