### ISSUE TITLE
Issue with Authorization Code

### ISSUE THREAD

**Issue by mcc85s** [MVKozlov/GMGoogleDrive#6]
Select-Object : Property "forms" cannot be found.
At C:\Development Tools\GMGoogleDrive\GMGoogleDrive\Public\Request-GDriveAuthorizationCode.ps1:106 char:37
+ ...           $forms = $ie.Document | Select-Object -ExpandProperty forms
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (System.__ComObject:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand
 
Request-GDriveAuthorizationCode : You cannot call a method on a null-valued expression.
At line:1 char:12
+ $code    = Request-GDriveAuthorizationCode -ClientID $oauth_json.web. ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Request-GDriveAuthorizationCode

----

I scoped out the module you wrote for this, is there a way to automate this for public access ? or is this strictly meant for manual use? I like the idea, it just seems a little short on automation details... Given all the hard work you apparently put into this... seems like it should be possible to automate

**Comment by mcc85s** [comment]
I tried to upload some files with gci -path ... -recurse

didn't like that very much lol

**Comment by MVKozlov** [comment]
Since google update it's authorization form cmdlet `Request-GDriveAuthorizationCode` seems doesn't work in unattended mode

**Comment by MVKozlov** [comment]
>I tried to upload some files with gci -path ... -recurse

what do you mean ? `Add-GDriveItem` does not support pipeline for now

**Comment by mcc85s** [comment]
I mean it actually uploaded most of my files that way, but I think it has the same general error that 7z has when you try to pipeline a folder structure, if the folders are duplicated ( since multiple files in a folder would mean that... ) then it just errors out.

It did manage to upload everything minus the correct paths, just a lot of errors lol. I think if anything it might just need a verification property or progress indicator in order to pipeline with it. I don't know that though.

I'd be more than happy to help you out if you're doing this on your own, there's quite a lot of code to sift through though, I might have some ideas on how to help.

**Comment by MVKozlov** [comment]
I move pipeline discussion to another topic for consistence (#7)

...And about authorization.
The idea of `Request-GDriveAuthorizationCode` was to automate getting the code, but this procedure should stay manually controlled and not used in any fully automated scripts

I can not understand why your attempt to use it failed. When I try to run it, everything stops at the last stage, where I have to allow access, but not before. Perhaps Google shows forms differently for different locations

**Comment by haranadh2501** [comment]
Hi Sir @MVKozlov , can u please guide me how to import your module into my script. it is very useful for me.

**Comment by MVKozlov** [comment]
@haranadh2501 
did you read the instructions in readme?
what exactly remained incomprehensible?
